final List<String> campusList = [
  'Aryabhatt DSEU Ashok Vihar Campus',
  'Ambedkar DSEU Shakarpur Campus - I',
  'Bhai Parmanand DSEU Shakarpur Campus - II',
  'G.B. Pant DSEU Okhla-I Campus',
  'DSEU Okhla-II Campus',
  'GB Pant DSEU Okhla-III Campus',
  'Guru Nanak Dev DSEU Rohini Campus',
  'DSEU Pusa Campus',
  'DSEU Dwarka Campus',
  'DSEU Siri Fort Campus',
  'Kasturba DSEU Pitampura Campus',
  'Meerabai DSEU Maharani Bagh Campus',
  'DSEU Rajokri Campus',
  'DSEU Vivek Vihar Campus',
  'DSEU Wazirpur-I Campus',
  'Centre for Healthcare, Allied Medical and Paramedical Sciences',
  'DSEU Dheerpur Campus',
  'DSEU Mayur Vihar Campus',
];

final List<String> rolesList =[
  'contractor',
  'worker',
];

final List<String> skills = [
  'Carpentry',
  'Masonry',
  'Plumbing',
  'Welding',
  'Electrical Wiring',
  'Painting',
  'Concrete Work',
  'Roofing',
  'Flooring Installation',
  'Drywall Installation',
  'Landscaping',
  'Tile Setting',
  'Bricklaying',
  'Paving',
  'Demolition',
  'Scaffolding',
  'Window Installation',
  'HVAC (Heating, Ventilation, and Air Conditioning)',
  'Automotive Repair',
  'Metal Fabrication',
  'Heavy Equipment Operation',
  'Framing',
  'Insulation Installation',
  'Plastering',
  'Cabinet Making',
  'Fence Installation',
  'Pipefitting',
  'Tiling',
  'Drywall Finishing',
  'Roof Repair',
  'Concrete Finishing',
  'Excavation',
  'Stucco Application',
  'Carpet Installation',
  'Masonry Restoration',
  'Glass Installation',
  'Solar Panel Installation',
  'Asphalt Paving',
  'Tree Trimming',
  'Irrigation System Installation',
  'Locksmithing',
  'Flooring Refinishing',
  'Siding Installation',
  'Deck Building',
  'Gutter Installation',
  'Power Washing',
  'Septic System Maintenance',
  'Chimney Sweeping',
  'Metal Roofing Installation',
  'Foundation Repair',
  'Pool Maintenance',
  'Pest Control',
  'Window Cleaning',
  'Carpet Cleaning',
  'Appliance Repair',
  'Grout Repair',
  'Epoxy Flooring Installation',
  'Fencing Repair',
  'Junk Removal',
  'Pressure Washing',
  'Elevator Repair',
  'Playground Equipment Installation',
  'Playground Maintenance',
  'Conveyor Belt Repair',
  'Commercial Kitchen Equipment Repair',
  'Refrigeration Repair',
  'Fire Sprinkler System Installation',
  'Lawn Mowing',
  'Snow Removal',
  'Irrigation System Repair',
  'Welding Inspection',
  'Traffic Signal Installation',
  'Road Marking',
  'Bridge Inspection',
  'Water Well Drilling',
  'Geotechnical Drilling',
  'Fertilizer Application',
  'Seed Planting',
  'Oil Rig Maintenance',
  'Water Tank Installation',
  'Silo Construction',
  'Elevator Installation',
  'Steel Erection',
  'Log Splitting',
  'Hardscaping',
  'Staircase Construction',
  'Awning Installation',
  'Playground Surfacing Installation',
  'Satellite Dish Installation',
  'Exterior Lighting Installation',
  'Fence Painting',
  'Deck Staining',
  'Erosion Control',
  'Asbestos Removal',
  'Hazardous Waste Disposal',
  'Snow Fence Installation',
  'Playground Fence Installation',
  'Bollard Installation',
  'Bollard Painting',
  'Anti-Graffiti Coating Application',
];



final Map<String, List<String>> campusCourses = {
  'Aryabhatt DSEU Ashok Vihar Campus': ['BCA', 'BBA', 'DCE', 'MLT'],
  'Ambedkar DSEU Shakarpur Campus - I': ['B.Tech', 'M.Tech', 'DCE'],
  'Bhai Parmanand DSEU Shakarpur Campus - II': ['BCA', 'MLT', 'BBA'],
  'G.B. Pant DSEU Okhla-I Campus': ['B.Tech', 'M.Tech'],
  'DSEU Okhla-II Campus': ['BCA', 'BBA'],
  'GB Pant DSEU Okhla-III Campus': ['DCE', 'MLT'],
  'Guru Nanak Dev DSEU Rohini Campus': ['BBA', 'MLT', 'B.Tech'],
  'DSEU Pusa Campus': ['BCA', 'DCE', 'B.Tech'],
  'DSEU Dwarka Campus': ['MLT', 'B.Tech'],
  'DSEU Siri Fort Campus': ['BCA', 'BBA'],
  'Kasturba DSEU Pitampura Campus': ['B.Tech', 'M.Tech'],
  'Meerabai DSEU Maharani Bagh Campus': ['BCA', 'BBA'],
  'DSEU Rajokri Campus': ['DCE', 'MLT'],
  'DSEU Vivek Vihar Campus': ['B.Tech', 'M.Tech'],
  'DSEU Wazirpur-I Campus': ['BCA', 'BBA', 'DCE', 'MLT'],
  'Centre for Healthcare, Allied Medical and Paramedical Sciences': ['BCA', 'BBA', 'DCE'],
  'DSEU Dheerpur Campus': ['MLT', 'B.Tech'],
  'DSEU Mayur Vihar Campus': ['BCA', 'BBA', 'DCE', 'MLT', 'B.Tech', 'M.Tech'],
};
