// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzJCaPNfID3CaR8gQLsdG7pmflHMgI92A',
    appId: '1:631684500010:web:b6ed1c68bac2b1fbc75153',
    messagingSenderId: '631684500010',
    projectId: 'dihadi-authentication',
    authDomain: 'dihadi-authentication.firebaseapp.com',
    storageBucket: 'dihadi-authentication.appspot.com',
    measurementId: 'G-9CQLB9ZNWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBggnCi4BRhiUggkBUCLwvmOYM5DB11eVU',
    appId: '1:631684500010:android:3e6f05a775c4a9b7c75153',
    messagingSenderId: '631684500010',
    projectId: 'dihadi-authentication',
    storageBucket: 'dihadi-authentication.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkfIE9rc4VNjsOSCtp5zQqwom8hPoTtjc',
    appId: '1:631684500010:ios:324210e4632ba524c75153',
    messagingSenderId: '631684500010',
    projectId: 'dihadi-authentication',
    storageBucket: 'dihadi-authentication.appspot.com',
    iosBundleId: 'com.aditya.dihadi',
  );
}
